spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tradeboard
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  messages:
    basename: messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update