version: '3'
services:
  db:
    image: 'postgres:latest'
    container_name: trade_board_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tradeboard
    ports:
      - "5432:5432"
    volumes:
      - :/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: trade_board_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tradeboard #host.docker.internal
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - db
volumes:
  my-db: {}