package com.app.tradeboard.utils.Enums;

public enum ProductCategory {
    ELECTRONICS,
    CLOTHING_AND_ACCESSORIES,
    FURNITURE_AND_INTERIOR,
    BEAUTY_AND_HEALTH,
    CHILDREN_PRODUCTS,
    SPORT_AND_RECREATION,
    HOBBIES_AND_ENTERTAINMENT,
    AUTOMOBILES_AND_TRANSPORT
}
